baseURL = "https://tsudaidzuru.github.io/"
languageCode = "ja-jp"
defaultContentLanguage = "ja"
title = "Working in Japanese multinational electronics company"
theme = "PaperMod"
googleAnalytics = "G-5CSX1GTYZX"

# ビルド設定
publishDir = "docs"
enableRobotsTXT = true

# 言語設定
hasCJKLanguage = true

# 著者情報
[author]
  name = "Tsuda Idzuru"

# サイトパラメータ
[params]
  description = "Working in Japanese multinational electronics company"
  images = ["img/og-image.jpg"]  # OGP画像（必要に応じて追加）
  dateFormat = "2006年01月02日"
  customCSS = ["css/custom.css"]

# ソーシャルメディア設定
[params.social]
  twitter = "TsudaIdzuru"

# メニュー設定
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    name = "Techs"
    url = "/tech/"
    weight = 2
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3

# プライバシーとGDPR設定
[privacy]
  [privacy.twitter]
    enableDNT = true
    simple = true
  [privacy.youtube]
    privacyEnhanced = true

# 出力設定
[outputs]
  home = ["HTML", "RSS"]

# マークダウン設定
[markup]
  [markup.highlight]
    style = "dracula"
  [markup.goldmark.renderer]
    unsafe = true
    
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]