baseURL = 'https://tsudaidzuru.github.io'
languageCode = 'ja-jp'
title = 'A blog by a not-so-young man working for the Japanese electronics industry'
author = 'Tsuda Idzuru'
theme = 'Diary'
publishDir = "docs"
HasCJKLanguage = true
enableRobotsTXT = true


[Author]
  twitter = "TsudaIdzuru"